server {
    port = 8080
    port = ${?PORT}
    host = "0.0.0.0"
    host = ${?HOST}
}
jwt {
    audience = "incident-demo"
    audience = ${?JWT_AUDIENCE}

    issuer = "http://localhost:8080"
    issuer = ${?JWT_ISSUER}

    realm = "Incidents API"
    secret = "my secret"
    secret = ${?JWT_SECRET}
}
